### PR TITLE
SparkPost portable for use in Xamarin.iOS, Xamarin.Android (PCL Profile 7)

### PR DESCRIPTION
**Pull request by stefandevo**
This makes the client library available for use in Xamarin.iOS, Xamarin.Android and other compliant Portable libraries (PCL Profile 7)

### CODE REVIEW

**Comment by stefandevo** [comment]
You should create a Nuget package as well for this .Portable version.

**Comment by darrencauthon** [comment]
I've never had a separate library for Xamarin. So you are saying we should merge this and release a new version for Xamarin support, and then release a separate dll for Xamarin.Portable support?

**Comment by darrencauthon** [comment]
Oh I read this wrong the first time -- we should create a separate nuget package for the .Portable assembly.

**Comment by stefandevo** [comment]
Yes. Correct 😄

**Comment by darrencauthon** [comment]
@richleland I'll build the Portable lib with my Mac & Xamarin Studio later today & take care of the nuget package.  I'll add you as an owner.

**Comment by stefandevo** [comment]
@darrencauthon You don't need to build it on a Mac or Xamarin Studio. It's a portable PCL7 profile. You can build this perfectly on a Windows and Visual Studio machine!

**Comment by darrencauthon** [comment]
@stefandevo That is true, but I want to get this thing going under Xamarin.  I think most people around this project and org are OSX/Linux folks, but so far all of my development has been on Windows & VS.  I'd like to get in line... plus I think the automation, CI, etc tends to work better in the non-MS world.  Imagine these nuget packages deploying themselves...

I've built & deployed nuget packages with Xamarin, and this library is so simple I know it would work just fine with Mono.  :)

**Comment by darrencauthon** [comment]
I might just pop the nuget package at lunch with Windows (my day job is in VS), but that's still the direction I think the project should go.

**Comment by stefandevo** [comment]
No problem, of course you can build the package on osx :-)

**Comment by stefandevo** [comment]
Came along this https://github.com/YoloDev/elephanet repo. There is an automatic deploy to nuget :-)

**Pull request merged**
